force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Genre</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Movie__c/fields/LegacyId__c.field-meta.xml
<CustomField>
    <fullName>LegacyId__c</fullName>
    <label>LegacyId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>ReleaseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDB_id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_id__c</fullName>
    <externalId>true</externalId>
    <label>TMDB_id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Scripts</relationshipLabel>
    <relationshipName>Scripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Genre.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Action</fullName>
    </customValue>
    <customValue>
        <fullName>Adventure</fullName>
    </customValue>
    <customValue>
        <fullName>Animation</fullName>
    </customValue>
    <customValue>
        <fullName>Comedy</fullName>
    </customValue>
    <customValue>
        <fullName>Crime</fullName>
    </customValue>
    <customValue>
        <fullName>Drama</fullName>
    </customValue>
    <customValue>
        <fullName>Family</fullName>
    </customValue>
    <customValue>
        <fullName>Fantasy</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Horror</fullName>
    </customValue>
    <customValue>
        <fullName>Mystery</fullName>
    </customValue>
    <customValue>
        <fullName>Romance</fullName>
    </customValue>
    <customValue>
        <fullName>Science Fiction (API name: Science_Fiction)</fullName>
    </customValue>
    <customValue>
        <fullName>Thriller</fullName>
    </customValue>
    <customValue>
        <fullName>War</fullName>
    </customValue>
    <customValue>
        <fullName>Western</fullName>
    </customValue>
    <masterLabel>Genre</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/MovieJsonDataProcessor.cls
public class MovieJsonDataProcessor {
    public static List<Movie__c> buildNewMovies(List<MovieWrapper> movieData, Map<String, Script__c> scriptMap) {
        Map<String, Movie__c> existingMovies = getExistingMovies(movieData);
        Set<String> validGenres = getValidGenreList();
        List<Movie__c> newMovies = new List<Movie__c>();

        for (MovieWrapper movie : movieData) {
            if (!existingMovies.containsKey(movie.tmdb_id) && isValidGenre(movie.genre, validGenres)) {
                Movie__c newMovie = createMovie(movie, scriptMap);
                newMovies.add(newMovie);
            }
        }

        return newMovies;
    }

    private static Movie__c createMovie(MovieWrapper mv, Map<String, Script__c> scriptMap) {
        Movie__c movie = new Movie__c(
            LegacyId__c = mv.id,
            TMDB_id__c = mv.tmdb_id,
            Budget__c = mv.budget,
            Title__c = mv.name,
            genre__c = mv.genre,
            rating__c = mv.rating,
            Revenue__c = mv.revenue,
            ReleaseDate__c = Date.parse(mv.release_date.replace('/', '.'))
        );

        Script__c relatedScript = scriptMap.get(mv.script.id);
        movie.Script__c = relatedScript != null ? relatedScript.Id : null;

        return movie;
    }

    private static Map<String, Movie__c> getExistingMovies(List<MovieWrapper> movieData) {
        Set<String> tmdbIds = new Set<String>();
        for (MovieWrapper movie : movieData) {
            tmdbIds.add(movie.tmdb_id);
        }

        List<Movie__c> existingMovies = [
            SELECT Id, TMDB_id__c 
            FROM Movie__c 
            WHERE TMDB_id__c IN :tmdbIds
    	];

        Map<String, Movie__c> movieMap = new Map<String, Movie__c>();
        for (Movie__c movie : existingMovies) {
            movieMap.put(movie.TMDB_id__c, movie);
        }
    
        return movieMap;
    }

    private static Set<String> getValidGenreList() {
        Set<String> validGenres = new Set<String>();
        Schema.DescribeFieldResult genreField = Movie__c.Genre__c.getDescribe();
        for (Schema.PicklistEntry entry : genreField.getPicklistValues()) {
            validGenres.add(entry.getValue());
        }
        return validGenres;
    }

    private static Boolean isValidGenre(String genreString, Set<String> validGenres) {
        for (String genre : genreString.split(';')) {
            if (!validGenres.contains(genre.trim())) {
                return false;
            }
        }
        return true;
    }
}