force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/TMDB_id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_id__c</fullName>
    <externalId>true</externalId>
    <label>TMDB_id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MovieAddController.cls
public with sharing class MovieAddController {
    
    @AuraEnabled
    public static List<tmdbSearchMovieResult> searchMovies(String title) {
        tmdbSearchMovieResponse searchResponse = tmdb.searchMovie(title);
        return searchResponse.results;
    }
    
    @AuraEnabled
    public static void createMovieRecord(String movieId) {
        Movie__c newMovie = new Movie__c(
            TMDB_Id__c = movieId
        );
        insert newMovie;
    }
}