force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Script__c.field-meta.xml
<CustomField>
    <fullName>Script__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Script</label>
    <referenceTo>Script__c</referenceTo>
    <relationshipLabel>Movies</relationshipLabel>
    <relationshipName>Movies</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Script__c/Script__c.object-meta.xml
<CustomObject>
    <label>Script</label>
    <nameField>
        <label>Script Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scripts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Script__c/fields/Movie__c.field-meta.xml
<CustomField>
    <fullName>Movie__c</fullName>
    <label>Movie</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>Scripts</relationshipLabel>
    <relationshipName>Scripts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FullJsonProcessor.cls
public class FullJsonProcessor {
    private static List<MovieWrapper> movieData;

    public static void processMoviesJson(String jsonBody) {
        loadMovieData(jsonBody, true);
        createAndInsertMovies();
    }

    public static void processMoviesStaticResource(String staticResource) {
        loadMovieData(staticResource, false);
        createAndInsertMovies();
    }

    private static void loadMovieData(String source, Boolean isJson) {
        if (isJson) {
        	movieData = JsonHandler.parseJsonArrayContentViaString(source);
        } else {
            movieData = JsonHandler.parseJsonArrayContentViaStaticResourse(source); 
        }
    }

    private static void createAndInsertMovies() {
        Map<String, Script__c> existingScripts = ScriptJsonDataProcessor.getExistingScripts(movieData);
        List<Script__c> newScripts = ScriptJsonDataProcessor.createNewScripts(movieData, existingScripts);
        Map<String, Script__c> allScripts = ScriptJsonDataProcessor.mergeScriptMaps(existingScripts, newScripts);

        List<Movie__c> newMovies = MovieJsonDataProcessor.buildNewMovies(movieData, allScripts);

        if (!newMovies.isEmpty()) {
            insert newMovies;
        }
    }
}