force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Movie__c/fields/Budget__c.field-meta.xml
<CustomField>
    <fullName>Budget__c</fullName>
    <label>Budget</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDB_id__c.field-meta.xml
<CustomField>
    <fullName>TMDB_id__c</fullName>
    <externalId>true</externalId>
    <label>TMDB_id</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Movie__c/fields/TMDBSyncDate__c.field-meta.xml
<CustomField>
    <fullName>TMDBSyncDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>TMDBSyncDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Movie_Settings__c/Movie_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Movie Settings</label>
</CustomObject>

force-app/main/default/objects/Movie_Settings__c/fields/Load_From_Json__c.field-meta.xml
<CustomField>
    <fullName>Load_From_Json__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Load From Json?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/tests/MovieBatchTest.cls
@isTest
public class MovieBatchTest {
    @testSetup
    static void setup() {
        Movie_Settings__c movieSetting  = Movie_Settings__c.getOrgDefaults();
        movieSetting.Load_From_Json__c=true;
        upsert movieSetting;
        
        List<Movie__c> movies = new List<Movie__c>();
        movies.add(new Movie__c(tmdb_Id__c = '67890', TMDBSyncDate__c = Date.today().addMonths(-2)));
        movies.add(new Movie__c(tmdb_Id__c = '67891', TMDBSyncDate__c = Date.today().addMonths(2)));
        insert movies;
    }
    @isTest
    static void testMovieSyncBatch() {
        Test.setMock(HttpCalloutMock.class, new TmdbHttpCalloutMock());
       
        Test.startTest();     
        Database.executeBatch(new MovieSyncBatch()); 
       	Test.stopTest();      
        
        List<Movie__c> moviesUpd = [SELECT Title__c, Revenue__c, Rating__c, Poster_URL__c, Budget__c, TMDBSyncDate__c FROM Movie__c];
        System.assertEquals(Date.Today(), moviesUpd[0].TMDBSyncDate__c, 'TMDBSyncDate should be today');
        System.assertNotEquals(Date.Today(), moviesUpd[1].TMDBSyncDate__c, 'TMDBSyncDate should not be today');
    }
}