force-app/main/default/objects/Cast__c/Cast__c.object-meta.xml
<CustomObject>
    <label>Cast</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Casts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cast__c/fields/Character__c.field-meta.xml
<CustomField>
    <fullName>Character__c</fullName>
    <label>Character</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Actor.recordType-meta.xml
<RecordType>
    <fullName>Actor</fullName>
    <active>true</active>
    <label>Actor</label>
</RecordType>

force-app/main/default/objects/Movie__c/Movie__c.object-meta.xml
<CustomObject>
    <label>Movie</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CastDataProcessor.cls
public with sharing class CastDataProcessor {

    public static void processCasts(Map<Id, List<tmdbCastResponse.CastMember>> movieCastsMap) {
        Map<String, Contact> actorMap = ActorDataProcessor.buildActors(movieCastsMap);
        List<Cast__c> castsToInsert = buildCasts(movieCastsMap, actorMap);
        if (!castsToInsert.isEmpty()) {
            insert castsToInsert;
        }
    }

    private static List<Cast__c> buildCasts(Map<Id, List<tmdbCastResponse.CastMember>> movieCastsMap, Map<String, Contact> actorMap) {
        List<Cast__c> castsToInsert = new List<Cast__c>();
        for (Id movieId : movieCastsMap.keySet()) {
            for (tmdbCastResponse.CastMember castMember : movieCastsMap.get(movieId)) {
                Contact actor = actorMap.get(castMember.name);
                if (actor != null) {
                    castsToInsert.add(createCast(movieId, castMember, actor));
                }
            }
        }
        return castsToInsert;
    }

    private static Cast__c createCast(Id movieId, tmdbCastResponse.CastMember castMember, Contact actor) {
        return new Cast__c(
            Movie__c = movieId,
            Character__c = castMember.character,
            Actor__c = actor.Id
        );
    }
}